# Site settings
title: Lucas Tiago
description: Teste
baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://lucastiagooliveira.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lucas Tiago
user_description: Teste 
user_title: Data Science
email: lucastiagooliveira@gmail.com
#twitter_username: lorem_ipsum
github_username:  lucastiagooliveira
#gplus_username:  lorem_ipsum
linkedin_username: lucas-tiago-7a4a1362

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
